# Generated by Django 4.1.3 on 2023-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("logo", models.ImageField(upload_to="company")),
                ("phone_numbers", models.TextField(max_length=150)),
                ("address", models.TextField(max_length=150)),
                ("subtitle", models.CharField(max_length=300)),
                ("emails", models.TextField(max_length=150)),
                ("call_us", models.CharField(max_length=50)),
                ("email_us", models.EmailField(max_length=254)),
                ("fb_link", models.URLField()),
                ("tw_link", models.URLField()),
                ("inst_link", models.URLField()),
            ],
        ),
    ]
