# Generated by Django 4.1.3 on 2023-01-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="fb_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
