# Generated by Django 4.1.3 on 2022-11-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_brand_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreviews",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_review",
                to="products.product",
            ),
        ),
    ]
