# Generated by Django 4.1.3 on 2023-03-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_brand_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="vediolink",
            field=models.URLField(blank=True, null=True),
        ),
    ]
