# Generated by Django 4.1.3 on 2023-04-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_vediolink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productreviews",
            name="image",
        ),
    ]
