# Generated by Django 4.1.3 on 2023-04-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_remove_productreviews_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreviews",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
